import { TargetProject, CorrelatedAsset } from '@/types/recon';

export const SAMPLE_PROJECTS: TargetProject[] = [
  {
    id: 'proj-acme-corp',
    name: 'Acme Financial Systems (HackerOne Scope)',
    domain: 'acmefinance.io',
    description: 'Programa público de Bug Bounty na HackerOne com ativos de infraestrutura cloud e APIs bancárias.',
    platform: 'hackerone',
    programUrl: 'https://hackerone.com/acme-security',
    createdAt: '2026-08-20T10:00:00Z',
    isDemo: true,
    inScope: ['*.acmefinance.io', '198.51.100.0/24', 'api.acmefinance.io', 'auth.acmefinance.io'],
    outOfScope: ['internal-admin.acmefinance.io', '198.51.100.254', 'payment-gateway.acmefinance.io'],
    policy: {
      platform: 'hackerone',
      programUrl: 'https://hackerone.com/acme-security',
      policySummary: 'Safe Harbor ativo. Testes permitidos com identificação obrigatória no cabeçalho HTTP.',
      safeHarbor: true,
      requiredHeaders: [
        {
          key: 'X-HackerOne-Research',
          value: 'w0rmingstar',
          description: 'Identificação obrigatória de pesquisador na HackerOne'
        }
      ],
      prohibitedVulns: ['DDoS', 'Social Engineering', 'Phishing'],
      extractedAt: '2026-08-24T20:00:00Z',
      targetArchitecture: 'cloud_native'
    },
    rules: [
      {
        id: 'rule-1',
        type: 'wildcard',
        pattern: '*.acmefinance.io',
        description: 'Todos os subdomínios principais da organização',
        isOutOfScope: false,
      },
      {
        id: 'rule-2',
        type: 'domain',
        pattern: 'internal-admin.acmefinance.io',
        description: 'Painel sensível de testes internos (Proibido tocar)',
        isOutOfScope: true,
      },
      {
        id: 'rule-3',
        type: 'cidr',
        pattern: '198.51.100.0/24',
        description: 'Faixa de rede de servidores AWS US-East',
        isOutOfScope: false,
      },
    ],
  },
  {
    id: 'proj-cloud-defense',
    name: 'CyberGrid Cloud Enterprise (HackerOne)',
    domain: 'cybergrid.tech',
    description: 'Superfície de ataque de infraestrutura Kubernetes e microsserviços.',
    platform: 'hackerone',
    programUrl: 'https://hackerone.com/cybergrid-bbp',
    createdAt: '2026-08-22T14:30:00Z',
    isDemo: true,
    inScope: ['*.cybergrid.tech', '203.0.113.0/24'],
    outOfScope: ['prod-vault.cybergrid.tech'],
    policy: {
      platform: 'hackerone',
      programUrl: 'https://hackerone.com/cybergrid-bbp',
      policySummary: 'Programa oficial HackerOne. Bug bounty para RCE, SSRF e Subdomain Takeover.',
      safeHarbor: true,
      requiredHeaders: [
        {
          key: 'X-HackerOne-Research',
          value: 'w0rmingstar',
          description: 'Identificação obrigatória'
        }
      ],
      prohibitedVulns: ['Physical Attacks', 'Spam'],
      extractedAt: '2026-08-24T20:00:00Z',
      targetArchitecture: 'microservices_api'
    },
    rules: [],
  },
];

export const SAMPLE_ASSETS: CorrelatedAsset[] = [
  {
    id: 'asset-api-acmefinance-io',
    subdomain: 'api.acmefinance.io',
    rootDomain: 'acmefinance.io',
    isAlive: true,
    httpStatus: 200,
    httpTitle: 'Acme Core Banking REST API v2',
    webServer: 'nginx/1.24.0 + gunicorn',
    contentLength: 4820,
    responseUrl: 'https://api.acmefinance.io/v2/docs',
    contentType: 'application/json; charset=utf-8',
    cnames: ['elb-us-east-1.amazonaws.com'],
    ips: ['198.51.100.12', '198.51.100.13'],
    ports: [
      { port: 80, protocol: 'tcp', state: 'open', service: 'http', product: 'nginx', version: '1.24.0' },
      { port: 443, protocol: 'tcp', state: 'open', service: 'https', product: 'nginx', version: '1.24.0' },
      { port: 8080, protocol: 'tcp', state: 'open', service: 'http-proxy', product: 'Spring Boot Actuator', banner: 'HTTP/1.1 200 OK' },
      { port: 9000, protocol: 'tcp', state: 'open', service: 'sonarqube', product: 'SonarQube API' },
    ],
    technologies: [
      { name: 'Nginx', version: '1.24.0' },
      { name: 'Spring Boot', version: '3.1.2' },
      { name: 'Swagger UI', version: '4.15.5' },
      { name: 'FastAPI' },
      { name: 'AWS ELB' },
    ],
    vulnerabilities: [
      {
        id: 'vuln-actuator-exposed',
        templateId: 'springboot-actuator-env-exposed',
        name: 'Spring Boot Actuator Exposed (/actuator/env)',
        severity: 'high',
        description: 'Endpoints de monitoramento do Spring Boot expostos sem autenticação contendo credenciais de banco e tokens.',
        matchedAt: 'https://api.acmefinance.io:8080/actuator/env',
        extractedResults: ['SPRING_DATASOURCE_PASSWORD=******', 'AWS_SECRET_ACCESS_KEY=******'],
        curlCommand: 'curl -i -s -k "https://api.acmefinance.io:8080/actuator/env"',
        cve: ['CVE-2020-5421'],
        cvssScore: 8.6,
        remediation: 'Desabilite endpoints desnecessários no application.properties via management.endpoints.web.exposure.exclude=*',
        sourceTool: 'nuclei',
        timestamp: '2026-08-24T18:45:10Z',
      },
      {
        id: 'vuln-swagger-leak',
        templateId: 'openapi-swagger-public-spec',
        name: 'Swagger API Schema Publicly Accessible',
        severity: 'medium',
        description: 'Definição completa da API REST e endpoints internos expostos via Swagger v3 JSON.',
        matchedAt: 'https://api.acmefinance.io/v2/api-docs',
        curlCommand: 'curl -s https://api.acmefinance.io/v2/api-docs | jq .',
        sourceTool: 'nuclei',
        timestamp: '2026-08-24T18:45:12Z',
      },
    ],
    cloudProvider: 'aws',
    takeoverRisk: false,
    firstSeen: '2026-08-24T18:30:00Z',
    lastUpdated: '2026-08-24T18:45:12Z',
    inScope: true,
    tags: ['api', 'critical-target', 'aws', 'spring-boot'],
  },
  {
    id: 'asset-auth-acmefinance-io',
    subdomain: 'auth.acmefinance.io',
    rootDomain: 'acmefinance.io',
    isAlive: true,
    httpStatus: 200,
    httpTitle: 'Acme Identity Provider (Keycloak)',
    webServer: 'Keycloak / Quarkus',
    contentLength: 12430,
    responseUrl: 'https://auth.acmefinance.io/auth/',
    contentType: 'text/html',
    cnames: ['auth-cluster.k8s.acmefinance.io'],
    ips: ['198.51.100.25'],
    ports: [
      { port: 443, protocol: 'tcp', state: 'open', service: 'https', product: 'Keycloak', version: '22.0.1' },
      { port: 8443, protocol: 'tcp', state: 'open', service: 'https-alt' },
    ],
    technologies: [
      { name: 'Keycloak', version: '22.0.1' },
      { name: 'OAuth2 / OIDC' },
      { name: 'Cloudflare CDN' },
    ],
    vulnerabilities: [
      {
        id: 'vuln-oauth-redirect',
        templateId: 'keycloak-open-redirect-misconfig',
        name: 'OIDC Client Open Redirect Misconfiguration',
        severity: 'medium',
        description: 'Validação permissiva no redirect_uri permitindo captura de token Authorization Code.',
        matchedAt: 'https://auth.acmefinance.io/auth/realms/acme/protocol/openid-connect/auth',
        curlCommand: 'curl -i "https://auth.acmefinance.io/auth/realms/acme/protocol/openid-connect/auth?client_id=account&redirect_uri=https://attacker.com"',
        sourceTool: 'nuclei',
        timestamp: '2026-08-24T18:45:15Z',
      },
    ],
    cloudProvider: 'cloudflare',
    takeoverRisk: false,
    firstSeen: '2026-08-24T18:30:00Z',
    lastUpdated: '2026-08-24T18:45:15Z',
    inScope: true,
    tags: ['auth', 'keycloak', 'oidc'],
  },
  {
    id: 'asset-blog-staging-acmefinance-io',
    subdomain: 'blog-staging.acmefinance.io',
    rootDomain: 'acmefinance.io',
    isAlive: true,
    httpStatus: 404,
    httpTitle: '404 Not Found - GitHub Pages / Fastly',
    webServer: 'GitHub.com',
    contentLength: 912,
    responseUrl: 'http://blog-staging.acmefinance.io',
    cnames: ['acmefinance-blog.github.io'],
    ips: ['185.199.108.153', '185.199.109.153'],
    ports: [
      { port: 80, protocol: 'tcp', state: 'open', service: 'http' },
      { port: 443, protocol: 'tcp', state: 'open', service: 'https' },
    ],
    technologies: [{ name: 'GitHub Pages' }, { name: 'Fastly CDN' }],
    vulnerabilities: [
      {
        id: 'vuln-subdomain-takeover-gh',
        templateId: 'github-pages-subdomain-takeover',
        name: 'High Impact Subdomain Takeover (GitHub Pages)',
        severity: 'critical',
        description: 'O CNAME aponta para "acmefinance-blog.github.io" que está órfão/desativado. Um atacante pode criar o repositório no GitHub e sequestrar o subdomínio.',
        matchedAt: 'blog-staging.acmefinance.io',
        extractedResults: ["There isn't a GitHub Pages site here."],
        curlCommand: 'dig CNAME blog-staging.acmefinance.io +short',
        cve: ['CVE-2019-XXXX'],
        cvssScore: 9.1,
        remediation: 'Remova a entrada DNS CNAME órfã ou reivindique o repositório correspondente no GitHub.',
        sourceTool: 'nuclei',
        timestamp: '2026-08-24T18:45:20Z',
      },
    ],
    cloudProvider: 'unknown',
    takeoverRisk: true,
    takeoverDetails: 'Dangling CNAME acmefinance-blog.github.io retornando "404 There isn\'t a GitHub Pages site here"',
    firstSeen: '2026-08-24T18:30:00Z',
    lastUpdated: '2026-08-24T18:45:20Z',
    inScope: true,
    tags: ['subdomain-takeover', 'critical', 'dangling-dns'],
  },
  {
    id: 'asset-jenkins-acmefinance-io',
    subdomain: 'ci-pipeline.acmefinance.io',
    rootDomain: 'acmefinance.io',
    isAlive: true,
    httpStatus: 200,
    httpTitle: 'Dashboard [Jenkins]',
    webServer: 'Jetty(9.4.43.v20210629)',
    contentLength: 21500,
    responseUrl: 'https://ci-pipeline.acmefinance.io',
    cnames: ['ec2-54-210-33-90.compute-1.amazonaws.com'],
    ips: ['54.210.33.90'],
    ports: [
      { port: 22, protocol: 'tcp', state: 'open', service: 'ssh', product: 'OpenSSH', version: '8.2p1' },
      { port: 80, protocol: 'tcp', state: 'open', service: 'http' },
      { port: 443, protocol: 'tcp', state: 'open', service: 'https', product: 'Jenkins', version: '2.346.1' },
      { port: 50000, protocol: 'tcp', state: 'open', service: 'jenkins-agent' },
    ],
    technologies: [
      { name: 'Jenkins CI', version: '2.346.1' },
      { name: 'Java / Jetty' },
      { name: 'Ubuntu Linux' },
    ],
    vulnerabilities: [
      {
        id: 'vuln-jenkins-unauth',
        templateId: 'jenkins-unauthenticated-read',
        name: 'Jenkins Read Access Without Authentication',
        severity: 'high',
        description: 'Painel do Jenkins CI permite leitura de builds, histórico de commits e logs de deployment publicamente.',
        matchedAt: 'https://ci-pipeline.acmefinance.io/api/json',
        curlCommand: 'curl -s https://ci-pipeline.acmefinance.io/api/json | jq .jobs[].name',
        cve: ['CVE-2022-29036'],
        cvssScore: 7.5,
        remediation: 'Configure controle de acesso baseado em matriz no Configure Global Security do Jenkins.',
        sourceTool: 'nuclei',
        timestamp: '2026-08-24T18:45:22Z',
      },
    ],
    cloudProvider: 'aws',
    takeoverRisk: false,
    firstSeen: '2026-08-24T18:30:00Z',
    lastUpdated: '2026-08-24T18:45:22Z',
    inScope: true,
    tags: ['ci-cd', 'jenkins', 'devops'],
  },
  {
    id: 'asset-git-acmefinance-io',
    subdomain: 'gitlab.acmefinance.io',
    rootDomain: 'acmefinance.io',
    isAlive: true,
    httpStatus: 200,
    httpTitle: 'GitLab Community Edition',
    webServer: 'nginx',
    contentLength: 9540,
    responseUrl: 'https://gitlab.acmefinance.io/users/sign_in',
    cnames: [],
    ips: ['198.51.100.40'],
    ports: [
      { port: 22, protocol: 'tcp', state: 'open', service: 'ssh' },
      { port: 80, protocol: 'tcp', state: 'open', service: 'http' },
      { port: 443, protocol: 'tcp', state: 'open', service: 'https' },
      { port: 9090, protocol: 'tcp', state: 'open', service: 'prometheus', product: 'Prometheus Metrics' },
    ],
    technologies: [
      { name: 'GitLab CE', version: '15.11' },
      { name: 'Ruby on Rails' },
      { name: 'Prometheus' },
      { name: 'PostgreSQL' },
    ],
    vulnerabilities: [
      {
        id: 'vuln-prometheus-metrics',
        templateId: 'prometheus-metrics-exposed',
        name: 'Prometheus Metrics Server Exposed (Port 9090)',
        severity: 'low',
        description: 'Métricas de consumo de hardware, nomes de servidores e queries internas expostas sem autenticação.',
        matchedAt: 'https://gitlab.acmefinance.io:9090/metrics',
        curlCommand: 'curl -s https://gitlab.acmefinance.io:9090/metrics | head -n 30',
        sourceTool: 'nuclei',
        timestamp: '2026-08-24T18:45:25Z',
      },
    ],
    cloudProvider: 'aws',
    takeoverRisk: false,
    firstSeen: '2026-08-24T18:30:00Z',
    lastUpdated: '2026-08-24T18:45:25Z',
    inScope: true,
    tags: ['git', 'metrics', 'internal-infra'],
  },
  {
    id: 'asset-cdn-acmefinance-io',
    subdomain: 'assets-static.acmefinance.io',
    rootDomain: 'acmefinance.io',
    isAlive: true,
    httpStatus: 200,
    httpTitle: 'CDN Static Distribution',
    webServer: 'AmazonS3',
    contentLength: 104,
    responseUrl: 'https://assets-static.acmefinance.io',
    cnames: ['d111111abcdef8.cloudfront.net'],
    ips: ['13.225.10.45', '13.225.10.92'],
    ports: [
      { port: 80, protocol: 'tcp', state: 'open', service: 'http' },
      { port: 443, protocol: 'tcp', state: 'open', service: 'https' },
    ],
    technologies: [{ name: 'CloudFront' }, { name: 'Amazon S3' }],
    vulnerabilities: [],
    cloudProvider: 'aws',
    takeoverRisk: false,
    firstSeen: '2026-08-24T18:30:00Z',
    lastUpdated: '2026-08-24T18:45:30Z',
    inScope: true,
    tags: ['cdn', 's3', 'static'],
  },
  {
    id: 'asset-corp-portal-acmefinance-io',
    subdomain: 'portal.acmefinance.io',
    rootDomain: 'acmefinance.io',
    isAlive: true,
    httpStatus: 200,
    httpTitle: 'Acme Financial - Home & Corporate Banking',
    webServer: 'Cloudflare',
    contentLength: 45020,
    responseUrl: 'https://portal.acmefinance.io',
    cnames: [],
    ips: ['104.21.40.12', '172.67.180.99'],
    ports: [
      { port: 80, protocol: 'tcp', state: 'open', service: 'http' },
      { port: 443, protocol: 'tcp', state: 'open', service: 'https' },
    ],
    technologies: [
      { name: 'React', version: '18.2' },
      { name: 'Next.js', version: '14.1' },
      { name: 'Cloudflare' },
      { name: 'Google Tag Manager' },
    ],
    vulnerabilities: [
      {
        id: 'vuln-info-cors',
        templateId: 'cors-misconfiguration-permissive',
        name: 'Overly Permissive CORS Policy (Origin Reflection)',
        severity: 'low',
        description: 'O servidor reflete qualquer cabeçalho Origin arbitrário com Access-Control-Allow-Credentials: true.',
        matchedAt: 'https://portal.acmefinance.io/api/user/session',
        curlCommand: 'curl -i -H "Origin: https://attacker.com" https://portal.acmefinance.io/api/user/session',
        sourceTool: 'nuclei',
        timestamp: '2026-08-24T18:45:33Z',
      },
    ],
    cloudProvider: 'cloudflare',
    takeoverRisk: false,
    firstSeen: '2026-08-24T18:30:00Z',
    lastUpdated: '2026-08-24T18:45:33Z',
    inScope: true,
    tags: ['production', 'web', 'banking'],
  },
];
